# Docker secrets configuration
# This file defines which Docker secrets should be created from environment variables
# Each secret maps a Docker secret name to an environment variable name

docker_secrets:
  - name: mysql_root_password
    env_var: MYSQL_ROOT_PASSWORD
  - name: wordpress_db_password
    env_var: WORDPRESS_DB_PASSWORD
  - name: traefik_basicauth
    env_var: TRAEFIK_BASICAUTH

# Add additional secrets here as needed for other stacks
# Example:
# - name: redis_password
#   env_var: REDIS_PASSWORD 