version: '3.8'

networks:
  socket_network:
    name: socket_network
    driver: overlay

services:
  docker-socket-proxy:
    image: linuxserver/socket-proxy:3.2.3
    # Ref https://github.com/Tecnativa/docker-socket-proxy?tab=readme-ov-file#grant-or-revoke-access-to-certain-api-sections
    environment:
      - NODES=1
      - INFO=1
      - SERVICES=1
      - TASKS=1
      - NETWORKS=1
      - CONTAINERS=1
      - EVENTS=1
      - BUILD=1
      - CONFIGS=1
      - GRPC=1
      - SWARM=1
      - SYSTEM=1
      - VOLUMES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
