version: '3.8'

networks:
  traefik_network:
    name: traefik_network
    driver: overlay
  monitor-net:
    name: monitor-net
    driver: overlay
  socket_network:
    name: socket_network
    driver: overlay

services:
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "443:443"
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.swarm=true
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.network=traefik_network
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Enable proxy protocol support for both HTTP and HTTPS entrypoints
      # Trust CloudStack network (192.168.1.0/24) AND Docker internal networks
      # Docker Swarm uses 10.0.0.0/8 and 172.16.0.0/12 for internal routing
      - --entrypoints.web.proxyProtocol.trustedIPs=192.168.1.0/24,10.0.0.0/8,172.16.0.0/12
      - --entrypoints.websecure.proxyProtocol.trustedIPs=192.168.1.0/24,10.0.0.0/8,172.16.0.0/12
      # Configure forwarded headers for the same network ranges
      - --entrypoints.web.forwardedHeaders.trustedIPs=192.168.1.0/24,10.0.0.0/8,172.16.0.0/12
      - --entrypoints.websecure.forwardedHeaders.trustedIPs=192.168.1.0/24,10.0.0.0/8,172.16.0.0/12
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - "--certificatesresolvers.letsencrypt.acme.email=admin@${DOMAIN_SUFFIX}"
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --metrics.prometheus=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt_data:/letsencrypt
    secrets:
      - traefik_basicauth
    networks:
      - traefik_network
      - monitor-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == manager-1
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_SUFFIX}`)
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.tls.certresolver=letsencrypt
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.middlewares.basic-auth.basicauth.usersFile=/run/secrets/traefik_basicauth
        - traefik.http.routers.traefik.middlewares=basic-auth@swarm


  docker-socket-proxy:
    image: linuxserver/socket-proxy:3.2.3
    # Ref https://github.com/Tecnativa/docker-socket-proxy?tab=readme-ov-file#grant-or-revoke-access-to-certain-api-sections
    environment:
      - NODES=1
      - INFO=1
      - SERVICES=1
      - TASKS=1
      - NETWORKS=1
      - CONTAINERS=1
      - EVENTS=1
      - BUILD=1
      - CONFIGS=1
      - GRPC=1
      - SWARM=1
      - SYSTEM=1
      - VOLUMES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  letsencrypt_data:

secrets:
  traefik_basicauth:
    external: true