---
- name: Perform a rolling reboot on servers requiring it
  hosts: all
  become: true
  serial: 1

  tasks:
    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      changed_when: false

    - name: Reboot if required
      reboot:
        msg: "Rebooting to apply kernel updates"
      when: reboot_required.stat.exists
