name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Deploy Environment
        env:
          CLOUDSTACK_API_KEY: ${{ secrets.CLOUDSTACK_API_KEY }}
          CLOUDSTACK_API_URL: ${{ secrets.CLOUDSTACK_API_URL }}
          CLOUDSTACK_SECRET_KEY: ${{ secrets.CLOUDSTACK_SECRET_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SECRETS_CONTEXT: ${{ toJSON(secrets) }}
        run: make deploy ENV=${{ github.event.inputs.environment }}
