version: '3.8'

services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_db_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp_network
    secrets:
      - mysql_root_password
      - wordpress_db_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == mysql
      resources:
        limits:
          memory: '{{ hostvars["mysql"]["available_memory_mb"] }}m'

  wordpress:
    image: wordpress:php8.3-apache
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - ingress_network
      - wp_network
    secrets:
      - wordpress_db_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == wp
      labels:
        - traefik.enable=true
        - traefik.http.routers.wordpress.rule=Host(`portal.{{ domain_suffix }}`)
        - traefik.http.routers.wordpress.entrypoints=websecure
        - traefik.http.routers.wordpress.tls.certresolver=letsencrypt
        - traefik.http.services.wordpress.loadbalancer.server.port=80
      resources:
        limits:
          memory: '{{ hostvars["wp"]["available_memory_mb"] }}m'

volumes:
  mysql_data:
  wordpress_data:

networks:
  wp_network:
    driver: overlay
  ingress_network:
    external: true

secrets:
  mysql_root_password:
    external: true
  wordpress_db_password:
    external: true 