version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "443:443"
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.swarm=true
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.network=app-network
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=admin@{{ domain_suffix }}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt_data:/letsencrypt
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == manager-1
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.{{ domain_suffix }}`)
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.tls.certresolver=letsencrypt
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_db_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    secrets:
      - mysql_root_password
      - wordpress_db_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == mysql

  wordpress:
    image: wordpress:php8.3-apache
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app-network
    secrets:
      - wordpress_db_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == wp
      labels:
        - traefik.enable=true
        - traefik.http.routers.wordpress.rule=Host(`portal.{{ domain_suffix }}`)
        - traefik.http.routers.wordpress.entrypoints=websecure
        - traefik.http.routers.wordpress.tls.certresolver=letsencrypt
        - traefik.http.services.wordpress.loadbalancer.server.port=80

volumes:
  letsencrypt_data:
  mysql_data:
  wordpress_data:

networks:
  app-network:
    driver: overlay

secrets:
  mysql_root_password:
    external: true
  wordpress_db_password:
    external: true 