version: '3.8'

services:
  echoserver:
    image: cilium/echoserver:1.10.3
    networks:
      - traefik_network
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.pool == echo
      labels:
        - traefik.enable=true
        - traefik.http.routers.echoserver.rule=Host(`echo.${DOMAIN_SUFFIX}`)
        - traefik.http.routers.echoserver.entrypoints=websecure
        - traefik.http.routers.echoserver.tls.certresolver=letsencrypt
        - traefik.http.services.echoserver.loadbalancer.server.port=80

networks:
  traefik_network:
    external: true
